### ISSUE TITLE
Possible to convert RPCS3 save to PS3 and vice versa?

### ISSUE THREAD

**Issue by kingjinxy** [Wulf2k/DeS-SaveEdit#4]
I have been trying to get my RPCS3 DeS save onto my PS3 to continue my playthrough there, but the game seems to have some sort of check for files that RPCS3 doesn't create. Is it possible to implement a conversion functionality into the save editor?

**Comment by Wulf2k** [comment]
The problem there is that PS3 uses a layer of encryption that RPCS3 doesn't.  It would be technically possible to include in the editor but a bit clunky, especially for a feature that wouldn't see much use.

A much better option would be to track down a copy of "Aldos' Bruteforce Save Data".  It's built for the specific purpose of decrypting/re-encrypting save data and should let you make that transfer between them.

**Comment by kingjinxy** [comment]
I have tried using Bruteforce Save Data, but I am not sure what I'm doing wrong. I tried following this guide: <https://old.reddit.com/r/rpcs3/comments/hhosvg/help_converting_demons_soul_save_from_rpcs3_to/>, but it doesn't seem to work for me.
