### ISSUE TITLE
Can only load slots other than 0 after writing to them (useless)

### ISSUE THREAD

**Issue by sonofevil** [Wulf2k/DeS-SaveEdit#6]
When you open a save file, Profile # 0 is preselected. You can use the "Open" button to load its properties. But you cannot open anything other 0. If you enter something other than 0 and click "Open", it immediately goes back to 0 and shows the properties of 0.

You can save to other profiles though. Once you've saved, the program "remembers" the current profile number, and you can "load" it. But that's useless because you just get the values you just saved. There seems to be no way to load the initial values.

**Comment by sonofevil** [comment]
Actually, 1USER.DAT and 204USER.DAT are the only save files getting changed in my case, so only the first save slot.

**Comment by sonofevil** [comment]
Actually the only .DAT files that get changed are the ones corresponding to slot 1, no matter what I do.

**Comment by Wulf2k** [comment]
The "Profile #" refers to the profile # of the PS3 user account.  It only ever matters for decrypting/encrypting saves in multi-user setups on the original PS3, and is not a save slot indicator.

The ability to edit other save slots should absolutely be added, but this is not that.

**Comment by sonofevil** [comment]
Ah, alright. DeS also refers to slots as "profiles", hence the confusion.
